### ISSUE TITLE
New models of units and buildings

### ISSUE THREAD

**Issue by Philla7** [EE-modders/Empire-Earth-reborn#3]
Some models need animations and currently we can't implement them...
If someone who has programming knowledge to inspect and reverse engineer the .CEM file can help us, feel free.

**Comment by zocker-160** [comment]
We'll have to keep an eye on this project
https://github.com/coderbot16/cemconv

Maybe he can do some magic  ;)

**Comment by Philla7** [comment]
Indeed, but others are welcome too
