### ISSUE TITLE
DB editing

### ISSUE THREAD

**Issue by Philla7** [EE-modders/Empire-Earth-reborn#4]
Help needed to research and find every entry in all of the DB files...
Big credits to man who made DB Editor: https://github.com/Forlini91/Empire-Earth---DB-Editor

**Comment by AgraelEE** [comment]
but after we find them, we need to update db editor and we kinda can't now. Or we make a list of entry numbers and it's effect

**Comment by zocker-160** [comment]
yeah or we work with @Forlini91 together, so he can implement it in his DB Editor

**Comment by AgraelEE** [comment]
yeah that's the better way
