### ISSUE TITLE
New Menu Artworks and Lobby Artwork

### ISSUE THREAD

**Issue by zocker-160** [EE-modders/Empire-Earth-reborn#5]
maybe we have to move the buttons in the main menu a bit

**Comment by AgraelEE** [comment]
Maybe we can consider this already done

Or we can continue to other menu part, too

**Comment by zocker-160** [comment]
@AgraelEE AFAIK we did update the main menu artwork and buttons

what about the other menus?

**Comment by zocker-160** [comment]
otherwise if this is done, you can close the issue, we could reopen it later again

**Comment by AgraelEE** [comment]
We didn't touch other menus, i wasn't sure if we should do it
