### ISSUE TITLE
Increased Zoom mod

### ISSUE THREAD

**Issue by zocker-160** [EE-modders/Empire-Earth-reborn#6]

**Comment by zocker-160** [comment]
can we mark this as done? @AgraelEE 

AFAIK drexmod does this already, is that good enough?

**Comment by AgraelEE** [comment]
It should be fine, you can eventually modify his config file to increase it even more
Don't know any other way around for that as of now anyway

**Comment by zocker-160** [comment]
ok fine

**Comment by Linkinsoldier** [comment]
> It should be fine, you can eventually modify his config file to increase it even more
> Don't know any other way around for that as of now anyway

well this patch script here seems to be able to do a similar thing, but I think drexmod works pretty great!
https://github.com/j-frei/EmpireEarthZoomChanger

**Comment by zocker-160** [comment]
@Linkinsoldier I agree, I have checked that repo out some time ago, it is not very useful for us though, since it does change the values directly in the exe, which is something we try to avoid when possible.
